### ISSUE TITLE
图片

### ISSUE THREAD

**Issue by Xiao-M0** [Elilif/emacs-anki-helper#3]
您好,我看了很多遍`readme`,还是不太清楚图片卡片怎么实现的
我的操作是制作正面卡片后,再选择图片路径运行`anki-helper-make-two-sided-card`制作反面卡片
实际的结果如下
![image](https://github.com/Elilif/emacs-anki-helper/assets/115467839/72d41e33-40e6-4569-96d0-1a0cf0c63214)
预期的结果如下
![image](https://github.com/Elilif/emacs-anki-helper/assets/115467839/d615bbdb-8c87-449f-ac30-3decb43cb146)

**Comment by Elilif** [comment]
因为 `anki-helper-make-two-sided-card` 在设计时的使用场景是 org-mode 以外的模式，所以不会转换内容，现在应该可以了。

另外注意 `anki-helper-make-two-sided-card` 不会在原文中保存 notes id ，所以仅适合于不需要后续修改的情况。

**Comment by Xiao-M0** [comment]
我更新了插件
但是不太清楚是不是windows11的问题,错误如下
![image](https://github.com/Elilif/emacs-anki-helper/assets/115467839/b1372554-f982-455d-9599-b9ec7acdfe0a)
并且它还会复制latex公式生成的图片 (因为特殊原因,我配置中latex生成格式为png)
![image](https://github.com/Elilif/emacs-anki-helper/assets/115467839/6dea0c42-f8d8-4fa3-83a3-68ec2b5b9a97)

> 因为 `anki-helper-make-two-sided-card` 在设计时的使用场景是 org-mode 以外的模式

我在非org-mode是无法使用的(测试插件 [dashboard](https://github.com/emacs-dashboard/emacs-dashboard) 和 [fanyi](https://github.com/condy0919/fanyi.el) ),具体如下

![屏幕截图 2023-10-30 102032](https://github.com/Elilif/emacs-anki-helper/assets/115467839/6cc8e6da-daea-42b9-820f-e50d80a9354a)

echo area message:

![image](https://github.com/Elilif/emacs-anki-helper/assets/115467839/adab7553-ebe0-46a1-bcbe-3f630ba01bc8)

---

![image](https://github.com/Elilif/emacs-anki-helper/assets/115467839/57e22a9b-8249-4585-b475-a180ea814098)

echo area message:

![image](https://github.com/Elilif/emacs-anki-helper/assets/115467839/aa5cfce3-7730-403f-b732-eba6c1466860)

**Comment by Elilif** [comment]
> 我更新了插件
> 但是不太清楚是不是windows11的问题,错误如下

请修改 `anki-helper-media-directory` ，需要改成相应的 media 目录。


> 并且它还会复制latex公式生成的图片 (因为特殊原因,我配置中latex生成格式为png)

这是设计如此，我希望在 org-mode 中看到的和在 anki 中看到的结果一致。


> 我在非org-mode是无法使用的(测试插件 [dashboard](https://github.com/emacs-dashboard/emacs-dashboard) 和 [fanyi](https://github.com/condy0919/fanyi.el) ),具体如下

我在 windows 虚拟机上测试一下，使用 `anki-helper-set-front-region` 和 `anki-helper-make-two-sided-card` 是没问题的，麻烦检查您自己的配置或者在 emacs -Q 下测试:

![](https://i.imgur.com/65GEDP5.gif)

**Comment by Xiao-M0** [comment]
感谢，问题都解决了
